Repository simixsistemas/SuperMidia.Widgets, pull requests merged in 2019-06, with the labels that each got.

#5 Mais info no index, Template para novos ✨
  Loteria/README.md
  Loteria/preview.png
  Posts/README.md
  Posts/preview.png
  README.md
  Template/README.md
  Template/index.html
  Template/jquery.min.js
  Template/package.json
  Template/preview.png
  Template/styles.css
Labels: documentation, enhancement

#6 Alteracoes no post da redesocial
  Posts/bootstrap.min.css
  Posts/index.html
  Posts/jquery.min.js
  README.md
Labels: enhancement

#8 add doctype e img de preview pro post
  Posts/index.html
  Posts/preview.png
Labels: documentation

#9 Complemento da documentação do template 📋
  Posts/index.html
  Posts/preview.png
  Template/README.md
Labels: documentation

#7 Limitações, Rascunho da documentação template 📝
  README.md
  Template/README.md
Labels: documentation

#11 Reorganização da documentação 📝🔧
  README.md
  Template/README.md
Labels: documentation 📋

#12 Exemplo outros concursos Loterias
  Loteria/LotoFacil/README.md
  Loteria/LotoFacil/fonts/FTN45__W.ttf
  Loteria/LotoFacil/fonts/FTN45__W.woff
  Loteria/LotoFacil/fonts/FTN85__W.ttf
  Loteria/LotoFacil/fonts/FTN85__W.woff
  Loteria/LotoFacil/img/Lotofacil.png
  Loteria/LotoFacil/img/bg_destaqueInternas.jpg
  Loteria/LotoFacil/img/home-com-sorte.png
  Loteria/LotoFacil/index.html
  Loteria/LotoFacil/package-lock.json
  Loteria/LotoFacil/package.json
  Loteria/LotoFacil/preview.png
  Loteria/LotoFacil/scripts/helpers.js
  Loteria/LotoFacil/scripts/jquery.min.js
  Loteria/LotoFacil/styles/styles.css
  Loteria/MegaSena/README.md
  Loteria/MegaSena/fonts/FTN45__W.ttf
  Loteria/MegaSena/fonts/FTN45__W.woff
  Loteria/MegaSena/fonts/FTN85__W.ttf
  Loteria/MegaSena/fonts/FTN85__W.woff
  Loteria/MegaSena/img/bg_destaqueInternas.jpg
  Loteria/MegaSena/img/home-com-sorte.png
  Loteria/MegaSena/index.html
  Loteria/MegaSena/package-lock.json
  Loteria/MegaSena/package.json
  Loteria/MegaSena/preview.png
  Loteria/MegaSena/scripts/helpers.js
  Loteria/MegaSena/scripts/jquery.min.js
  Loteria/MegaSena/styles/styles.css
  Loteria/README.md
  Loteria/index.html
  Loteria/styles.css
  README.md
Labels: bug 🐛, documentation 📋, enhancement ✨

#13 Frase do dia ✨
  .gitignore
  Quotes/README.md
  Quotes/index.html
  Quotes/jquery.min.js
  Quotes/package.json
  Quotes/preview.gif
  Quotes/preview.png
  Quotes/simix-animations.css
  Quotes/styles.css
  Quotes/textFit.js
Labels: enhancement ✨
